name: portrait_click
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  badges: ^3.1.2
  cloud_firestore: ^4.8.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: null
  font_awesome_flutter: ^10.5.0
  image_picker: null
  intl: ^0.18.1
  like_button: ^2.0.5
  liquid_pull_to_refresh: ^3.0.1
  one_context: ^2.1.0
  page_transition: ^2.0.9
  provider: ^6.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/

  fonts:
    - family: San-Francisco
      fonts:
        - asset: assets/fonts/SF-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Bold.otf
          weight: 700
